// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ProductInput struct {
	ID          *string `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Qty         int     `json:"qty"`
	BasePrice   int     `json:"base_price"`
	CoverImage  *string `json:"cover_image"`
	CreatedAt   *string `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
	Deleted     *string `json:"deleted"`
}

type Products struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Qty         int     `json:"qty"`
	BasePrice   int     `json:"base_price"`
	CoverImage  *string `json:"cover_image"`
	CreatedAt   string  `json:"created_at"`
	UpdatedAt   *string `json:"updated_at"`
	Deleted     *string `json:"deleted"`
}

type Transaction struct {
	ID         string  `json:"id"`
	Status     string  `json:"status"`
	Date       *string `json:"date"`
	TotalPrice int     `json:"total_price"`
	Discount   *int    `json:"discount"`
	AdminsID   *string `json:"admins_id"`
	CreatedAt  string  `json:"created_at"`
	UpdatedAt  *string `json:"updated_at"`
	DeletedAt  *string `json:"deleted_at"`
	UserID     int     `json:"user_id"`
}

type TransactionDetails struct {
	ID            string  `json:"id"`
	Price         int     `json:"price"`
	ProductID     int     `json:"product_id"`
	TransactionID int     `json:"transaction_id"`
	CreatedAt     string  `json:"created_at"`
	UpdatedAt     *string `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
}

type TransactionDetailsInput struct {
	ID            *string `json:"id"`
	Price         int     `json:"price"`
	ProductID     int     `json:"product_id"`
	TransactionID int     `json:"transaction_id"`
	CreatedAt     *string `json:"created_at"`
	UpdatedAt     *string `json:"updated_at"`
	DeletedAt     *string `json:"deleted_at"`
}

type TransactionInput struct {
	ID         *string `json:"id"`
	Status     string  `json:"status"`
	Date       *string `json:"date"`
	TotalPrice *int    `json:"total_price"`
	Discount   *int    `json:"discount"`
	AdminsID   *string `json:"admins_id"`
	CreatedAt  *string `json:"created_at"`
	UpdatedAt  *string `json:"updated_at"`
	DeletedAt  *string `json:"deleted_at"`
	UserID     int     `json:"user_id"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     *string `json:"email"`
	Password  string  `json:"password"`
	Phone     *string `json:"phone"`
	Address   *string `json:"address"`
	Birthdate *string `json:"birthdate"`
	IsActive  *int    `json:"is_active"`
	CreatedAt string  `json:"created_at"`
	UpdatedAt *string `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type UserInput struct {
	ID        *string `json:"id"`
	Name      string  `json:"name"`
	Email     *string `json:"email"`
	Password  string  `json:"password"`
	Phone     *string `json:"phone"`
	Address   *string `json:"address"`
	Birthdate *string `json:"birthdate"`
	IsActive  *int    `json:"is_active"`
	CreatedAt *string `json:"created_at"`
	UpdatedAt *string `json:"updated_at"`
	DeletedAt *string `json:"deleted_at"`
}

type Variant struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Price      int     `json:"price"`
	CoverImage *string `json:"cover_image"`
	ProductID  int     `json:"product_id"`
}

type VariantInput struct {
	ID         *string `json:"id"`
	Name       string  `json:"name"`
	Price      int     `json:"price"`
	CoverImage *string `json:"cover_image"`
	ProductID  int     `json:"product_id"`
}
